[build]
  command = "npm run build"
  publish = ".next/standalone"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Cache-Control = "public, max-age=3600, must-revalidate"

[context.production]
  command = "npm run build"
  publish = ".next/standalone"

[context.preview]
  command = "npm run build"
  publish = ".next/standalone"

[context.deploy-preview]
  command = "npm run build"
  publish = ".next/standalone"

